# Taskfile.yml — root of rts-consul-observability
# Usage: task <task-name>
# Docs:  https://taskfile.dev
#
# Topology: API GW → web → api → [payments (→ currency → rates), cache]
#
# Quick start:
#   Docker:  task docker:up && task validate
#   K8s:     task k8s:up  && task validate

version: "3"

vars:
  CLUSTER: consul-observability

tasks:

  # ── Default ────────────────────────────────────────────────────────────────
  default:
    desc: "List all available tasks"
    silent: true
    cmds:
      - task --list

  # ── Docker ─────────────────────────────────────────────────────────────────

  docker:up:
    desc: "Start the full Docker Compose stack (Consul + fake-service + observability)"
    dir: docker
    cmds:
      - docker compose down --remove-orphans 2>/dev/null || true
      - docker compose up -d
      - |
        echo ""
        echo "✓ Stack is up. Run: task validate"
        echo ""
        echo "  Direct Envoy:  http://localhost:21000/"
        echo "  API Gateway:   http://localhost:21001/"

  docker:down:
    desc: "Stop Docker Compose and remove orphaned containers (volumes are kept)"
    dir: docker
    cmds:
      - echo "Stopping Docker Compose stack..."
      - docker compose down --remove-orphans
      - echo "✓ Done. Volumes are preserved. Run 'task docker:up' to restart."

  # ── Kubernetes ─────────────────────────────────────────────────────────────

  k8s:up:
    desc: "Bootstrap kind cluster with Consul + observability + fake-service"
    cmds:
      - bash scripts/kind-setup.sh

  k8s:down:
    desc: "Stop port-forwards and delete the kind cluster (full teardown)"
    cmds:
      - pkill -f 'kubectl port-forward' 2>/dev/null || true
      - kind delete cluster --name {{.CLUSTER}}
      - echo "✓ Cluster {{.CLUSTER}} deleted."

  # ── Demo / Fault injection ─────────────────────────────────────────────────

  demo:
    desc: "Interactive fault-injection demo — auto-detects Docker vs Kubernetes"
    cmds:
      - bash scripts/demo.sh

  # ── Validate ───────────────────────────────────────────────────────────────

  validate:
    desc: "Health check — auto-detects Docker vs Kubernetes, prints status + URLs"
    cmds:
      - |
        DOCKER_RUNNING=false
        K8S_RUNNING=false

        # Detect Docker
        if docker compose -f docker/docker-compose.yml ps --status running \
            --format json 2>/dev/null | grep -q '"web"'; then
          DOCKER_RUNNING=true
        fi

        # Detect K8s
        if kubectl get pods -n default -l 'app in (web,api)' \
            --no-headers 2>/dev/null | grep -q Running; then
          K8S_RUNNING=true
        fi

        if $DOCKER_RUNNING; then
          echo "╔══════════════════════════════════════════════════════════════╗"
          echo "║          Consul Observability Demo — Docker                  ║"
          echo "╠══════════════════════════════════════════════════════════════╣"
          echo "║  App (via Envoy)    http://localhost:21000/                   ║"
          echo "║  API Gateway        http://localhost:21001/                   ║"
          echo "║  Consul UI          http://localhost:8500                     ║"
          echo "║  Grafana            http://localhost:3000  (admin/admin)      ║"
          echo "║  Jaeger             http://localhost:16686                    ║"
          echo "║  Prometheus         http://localhost:9090                     ║"
          echo "╚══════════════════════════════════════════════════════════════╝"
          echo ""
          echo "── Service status ──"
          docker compose -f docker/docker-compose.yml ps --format "table {{.Name}}\t{{.Status}}"
          echo ""
          echo "── Quick checks ──"
          curl -sf http://localhost:8500/v1/status/leader | xargs -I{} echo "  Consul leader: {}" || echo "  Consul: NOT READY"
          curl -sf http://localhost:9090/-/ready          && echo "  Prometheus: READY"          || echo "  Prometheus: NOT READY"
          curl -sf http://localhost:3100/ready            && echo "  Loki: READY"                || echo "  Loki: NOT READY"
          curl -sf http://localhost:21000/ >/dev/null     && echo "  Web (Envoy): READY"         || echo "  Web: NOT READY"
          curl -sf http://localhost:21001/ >/dev/null     && echo "  API Gateway: READY"         || echo "  API Gateway: NOT READY"

        elif $K8S_RUNNING; then
          echo "╔══════════════════════════════════════════════════════════════╗"
          echo "║          Consul Observability Demo — Kubernetes              ║"
          echo "╠══════════════════════════════════════════════════════════════╣"
          echo "║  App (web service)  http://localhost:9090  (port-forward)    ║"
          echo "║  API Gateway        http://localhost:18080  (NodePort 30004) ║"
          echo "║  Consul UI          http://localhost:8500  (port-forward)    ║"
          echo "║  Grafana            http://localhost:3000  (admin/admin)     ║"
          echo "║  Jaeger             http://localhost:16686 (port-forward)    ║"
          echo "║  Prometheus         http://localhost:9091  (port-forward)    ║"
          echo "╠══════════════════════════════════════════════════════════════╣"
          echo "║  Port-forwards:                                              ║"
          echo "║    kubectl port-forward svc/web          9090:9090 -n default       ║"
          echo "║    kubectl port-forward svc/consul-ui    8500:80   -n consul        ║"
          echo "║    kubectl port-forward svc/grafana      3000:3000 -n observability ║"
          echo "║    kubectl port-forward svc/jaeger-query 16686:16686 -n observability ║"
          echo "║    kubectl port-forward svc/prometheus   9091:9090 -n observability ║"
          echo "╚══════════════════════════════════════════════════════════════╝"
          echo ""
          echo "── fake-service pods ──"
          kubectl get pods -n default -l 'app in (web,api,payments,currency,cache,rates)' 2>/dev/null || echo "  (no pods found)"
          echo ""
          echo "── Observability pods ──"
          kubectl get pods -n observability 2>/dev/null || echo "  (no observability namespace)"
          echo ""
          echo "── Consul services ──"
          kubectl exec -n consul consul-server-0 -- consul catalog services 2>/dev/null || echo "  (consul not ready)"

        else
          echo "No running stack detected."
          echo "  Docker:  task docker:up"
          echo "  K8s:     task k8s:up"
          exit 1
        fi
