{
 "title": "Service Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source_service",
    "query": {
     "query": "label_values(consul_source_service)"
    }
   },
   {
    "name": "destination_service",
    "query": {
     "query": "label_values(consul_destination_service)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Services Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services with High Error Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\", consul_destination_service!=\"\"}[5m])) \n    by (local_cluster, consul_destination_service) \n    / \n    sum(irate(envoy_cluster_upstream_rq_xx{consul_destination_service!=\"\"}[5m])) \n    by (local_cluster, consul_destination_service)\n  )\n) * 100 > 1",
     "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_destination_service!~\"\"}[5m])) by (le,local_cluster, consul_destination_service))",
     "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{consul_destination_service!=\"\", consul_source_service!=\"mesh-gateway\"}[5m])) by (local_cluster, consul_destination_service) ",
     "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
    }
   ]
  },
  {
   "title": "Upstream Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{consul_destination_service!=\"\", consul_source_service!=\"mesh-gateway\"}) by (local_cluster, consul_destination_service)",
     "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
    }
   ]
  },
  { "title": "Circuit Breaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Circuit Breakers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (envoy_cluster_outlier_detection_ejections_active{consul_destination_service!~\"\", local_cluster!=\"mesh-gateway\"}) by (local_cluster, consul_destination_service)",
     "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
    }
   ]
  },
  {
   "title": "Circuit Breakers Triggered",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_outlier_detection_ejections_consecutive_5xx{consul_destination_service!~\"\", local_cluster!=\"mesh-gateway\"}[$__range])) by (consul_destination_service)",
     "legendFormat": "{{consul_destination_service}}"
    }
   ]
  }
 ]
}