# openshift/consul/route.yaml
# OpenShift Route for the Consul UI.
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: consul-ui
  namespace: consul
spec:
  to:
    kind: Service
    name: consul-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
